export { HandlerRegistry } from './registry.js';
export { evaluate } from './evaluator.js';
export { validateAST } from './validator.js';
export { createDefaultRegistry } from './handlers/index.js';
export type { HandlerDefinition, EvaluateFn } from './handler.js';
export { resolveValue, getNestedValue, isFieldReference, isDataReference } from './resolve.js';
export { makeSuccess, makeFailure, makeTrace } from './result.js';
export { Simulator } from './simulator.js';
export type { TestCase, ValidationSuite, TestCaseResult, SimulatorReport } from './simulator.js';
export { portfolioDiff, type PortfolioDiffInput, type PortfolioDiffResult, type StatusChange, type EntityRecord } from './portfolio-diff.js';
